'''
Name:           Faruq Quotes
Version:        1
Description:    Faruq battle bot quotes for Hannah
Tips:           You can use co-pilot to generate a list of Faruq quotes
'''

import streamlit as st
import random

quotes_list = [
"Ladies and gentlemen, are you ready? It’s Robot Fighting Time!",
"Robots, activate!",
"Red team, ready?",
"Blue team, ready?",
"Let the bot battle begin!",
"The results from the judges are in.",
"We have a split decision.",
"It’s time for the main event!",
"Let’s get ready to rumble!",
"Are you ready for some robot carnage?",
"It’s time to unleash the bots!",
"Who will be the last bot standing?",
"Let’s see some sparks fly!",
"Prepare for battle!",
"It’s time to settle the score!",
"Let the destruction begin!",
"Who will reign supreme?",
"It’s a clash of the titans!",
"Only one bot will emerge victorious!",
"It’s a fight to the finish!",
"Let’s see some metal mayhem!",
"Who will be the ultimate champion?",
"It’s time for some robot warfare!",
"Let’s see who has the best bot!",
"It’s a battle of the bots!",
"Who will be the king of the ring?",
"It’s time for some robot action!",
"Let’s see who has the toughest bot!",
"It’s a fight for survival!",
"Who will be the last bot standing?",
"It’s time for some robot destruction!",
"Let’s see who has the best strategy!",
"It’s a battle of wits and strength!",
"Who will come out on top?",
"It’s time for some robot combat!",
"Let’s see who has the most powerful bot!",
"It’s a fight to the death!",
"Who will be the ultimate victor?",
"It’s time for some robot mayhem!",
"Let’s see who has the best design!",
"It’s a battle of engineering!",
"Who will be the last bot standing?",
"It’s time for some robot chaos!",
"Let’s see who has the best tactics!",
"It’s a fight for dominance!",
"Who will be the ultimate champion?",
"It’s time for some robot destruction!",
"Let’s see who has the best skills!",
"It’s a battle of the best!",
"Who will be the last bot standing?",
"It’s time for some robot warfare!",
"Let’s see who has the best bot!",
"It’s a fight to the finish!",
"Who will be the ultimate victor?",
"It’s time for some robot mayhem!",
"Let’s see who has the best strategy!",
"It’s a battle of wits and strength!",
"Who will come out on top?",
"It’s time for some robot combat!",
"Let’s see who has the most powerful bot!",
"It’s a fight to the death!",
"Who will be the ultimate champion?",
"It’s time for some robot destruction!",
"Let’s see who has the best design!",
"It’s a battle of engineering!",
"Who will be the last bot standing?",
"It’s time for some robot chaos!",
"Let’s see who has the best tactics!",
"It’s a fight for dominance!",
"Who will be the ultimate victor?",
"It’s time for some robot mayhem!",
"Let’s see who has the best skills!",
"It’s a battle of the best!",
"Who will be the last bot standing?",
"It’s time for some robot warfare!",
"Let’s see who has the best bot!",
"It’s a fight to the finish!",
"Who will be the ultimate champion?",
"It’s time for some robot destruction!",
"Let’s see who has the best strategy!",
"It’s a battle of wits and strength!",
"Who will come out on top?",
"It’s time for some robot combat!",
"Let’s see who has the most powerful bot!",
"It’s a fight to the death!",
"Who will be the ultimate victor?",
"It’s time for some robot mayhem!",
"Let’s see who has the best design!",
"It’s a battle of engineering!",
"Who will be the last bot standing?",
"It’s time for some robot chaos!",
"Let’s see who has the best tactics!",
"It’s a fight for dominance!",
"Who will be the ultimate champion?",
"It’s time for some robot destruction!",
"Let’s see who has the best skills!"
]

random_quote = random.randint(0,len(quotes_list)-1)
st.write("Faruq Quote #" + str(random_quote+1) + ". " + quotes_list[random_quote])
