# Used with faruq_quotes_v2.py

faruq_quotes_list = [

# General
"It's ROBOT fightin' time!",

# SAWBLAZE
"He's so mean his opponents scream, Please, don't blaze me, bro! It's SAWBLAZE!",
"Say hello to Jamison Go. His old team broke up like The Beatles so he went solo. It's SAWBLAZE!",
"Kids, come in for recess, it's about to be nap time. We may not be on the playground, but I do see-saw. It's SAWBLAZE!",
"This bot will cut you with hot steel like you're a three-course meal. It's time to make reservations at T.G. Die Friday's. It's SAWBLAZE!",
"Rock beats scissors, scissors beat paper. This is a stupid game because fire and saw beats them all. It's SAWBLAZE!",
"Prepare to be amazed by a blade that's also ablaze. It'll cut you like butter before you can utter Please, stop burnin' me, man! It's SAWBLAZE!",
"This bot's favorite dance is... the robot. Here to breakdance all over you, it's SAWBLAZE!",
"This bot comes in fast with saws ablazing and vicious attacks that are hair-raising. It's SAWBLAZE!",
"With a saw and flames that burn kind of greenie. It'll roast your buns like a cocktail weenie. Relish in the glory of SAWBLAZE!",
"It's a regular New England Slay-triot. Put on your dad socks, you're about to be Boston Ruined by SAWBLAZE!",
"It's scarier than the Alien and it's going to Ripley you up. Green flames like the acid in a Xenomorph's veins. You better have a plan, cause it's game over man! I've got a bad feeling about this bot. It's SAWBLAZE!",
"From MIT, they blaze, they saw, they conquer. SAWBLAZE!",
"Are you a glutton for punishment? If not, better run. It's the #7 seed that's the seven deadly sins, wrapped in one. Everyone prays, but everyone pays. It's SAWBLAZE!",
"At lucky number seven, it's the flaming green machine from MIT. So hot, it gets jalapeno business, G. It's nacho lucky. It's the spicy slicey, SAWBLAZE!",
"This bot comes fast, its saw's a-blazing. Bringing the heat, it's temperature raising. Putting you through punishment like it was hazing, and I also got to admit, the engineer's hair is amazing. Give it up for SAWBLAZE!",
"His giant blade can chop opponents down to a smaller height. And what he's cooking up can give you a buzz like his name was Walter White. We all have fun here on BattleBots, win, lose or draw, but if you want your opponents to be Breaking Bad, you better call Saw. Now, say his name... it's SAWBLAZE!",
"This bot's engineer is a college drop-out like Kanye. In the box, he's heartless and cooks opponents like entrees. Now he's watching the throne and his ambitions are bigger. He won't settle for silver or bronze. He's a gold digger. This bot is back and he's in his prime. And yo, I'mma let you finish, but SAWBLAZE is the greatest robot of all time! Give it up for SAWBLAZE!",
"It's got a saw and a flame that burns kind of green-y. It'll roast your buns like a cocktail weenie. Relish in the glory of SAWBLAZE!",
"Like chocolate and peanut butter, mmm-mmm, or PB&J, two great tastes that taste great together can waste bots all day. This potent pairing will make you remember his name. You've got fire in my buzzsaw. You've got blade in my flame. Here to cut you into pieces like Reese's, it's SAWBLAZE!",
"From Cambridge, Massachusetts, your championship dreams are about to go up in flames against SAWBLAZE!",
"From Cambridge, Massachusetts, it came, it saw, it blazed. It's SAWBLAZE!",
"From Cambridge, Mass., he's got a vertical saw to murder you all. It's SAWBLAZE!",
"This bot's from the home of MIT, and if I had to take a guess, that stands for mutilating, impaling, and torturing 'cause that's what he does best. He graduated magna cum laude at the top of his class and earned a master's degree in kicking your ass, with a minor in communications, of course. Give it up for SAWBLAZE!",
"This means got the green light. No time to stop. Let's Jamison Go. His trigger finger must be a green thumb, cause look at your terror run. You'll be green around the gills when his six saw starts to shred. And when you see what he's done to your body, you'll be green with envy for the day. It's SAWBLAZE!",
"This bot swings a blade like Conan the Barbarian and has no sense of humor. It'll give you a splitting headache, but don't worry. It's not a tumor. Thinking you beat him is True Lies, and when this Terminator attacks, you can just call the cemetery and tell them, 'I'll be back. Hasta la vista, baby.' It's SAWBLAZE!",
"From Cambridge, Massachusetts, he came, he saw, he sawed some more. Give it up for SAWBLAZE!",
"From Cambridge, Massachusetts. Remember that FDR quote? 'The only thing we have to fear is giant spinning blades and flame throwers.' I'm paraphrasing but you get it. It's SAWBLAZE!",
"The reigning world champion's taking a shot at perfection. He's got the Nut. Now he'll add a Golden Bolt to his collection. He Natty Iced the SHREDDIT BROs. They couldn't handle the horror. TANTRUM tried to pitch a fit. But he put baby in the corner. Now he's hunting big game, it's the end of their days, and when he's left with the Bolt, all that'll be left is a blaze. It's SAWBLAZE!",

# TANTRUM
"It'll make you a bigger crybaby than Tom Brady! Aw come on, you think I care if Boston fans hate me? It's TANTRUM!",
"Knock knock. (Who's there?) Boo. (Boo who?) Open the door and I'll give you somethin' to cry about. It's TANTRUM!",
"Get ready to get slapped around 'til you cry I'm so... *sobbing* scared *sobbing* ... It's TANTRUM!",
"Throwing a fit until other bots quit. It's going to lower the boom or get sent to its room. It's TANTRUM!",
"It might have a baby face, but it's armed with some adult teeth. There's nothing minor about this meltdown, son. *Cries, yells, and runs around the box* It's TANTRUM!",
"This bots battle cry is gimme gimme gimme, my my my! It needs to go to the naughty chair, but it won't stay there. It's TANTRUM!",
"This bot never quits and it throws giant fits. It'll scream and hit the floor like a six year old in a toy story. But mommy, mommy, I want more. It's TANTRUM!",
"Throwing a fit until other bots quit. It's going to give you the boom or get sent to its room. It's TANTRUM!",
"This bot packs a punch like bottomless mimosa brunch. It's TANTRUM!",
"It's got the fist of rage to split your face. Give it up for TANTRUM!",
"When you throw a TANTRUM, you'll scream and cry, but when you throw down with this TANTRUM, you'll bleed and die. If you wanna feel that championship glory, you'll have to contend with his little fist of fury. It's TANTRUM!",
"From Cambridge, Massachusetts, the only pacifier for this bot is murder. It's TANTRUM!",
"Aren's new bot bit the dust but his squad's got the trump card. Ginger and Alex will make Jake's bot break and toss it right in the junkyard. Revenge is a dish best served for clenched fists and this team's ready to pound. They're not afraid of the son of the Son of Whyachi and tonight, the son goes down! It's TANTRUM!",
"This crybaby will hit you so hard, you'll have to call the wham-bulance, it's TANTRUM!",
"Play this game of death and you'll get popped in the chops. He throws hands like Bruce Lee and his fists of fury don't stop. Jeet Kune Don't test him because he's earned his clout and when he enters the box, they'll be dragging you out. It's TANTRUM!",
"This slap-happy bot got the smacks that brings pain. Don't call him G.I. Jane or he'll go G.T. insane. You'll get Chris Rocked in the jaw, your odds of winning are going south. So keep this bot's name out your mouth. It's TANTRUM!",
"What's up? I hope you're ready to fight, son. This bot will come at you like he's Mike Tyson. So beware to hit the hammer, stay clear or suffer the fate of Holyfield's ear. It's TANTRUM!",
"He'll throw a giant fit like Christian Bale did. Or when Tyra Banks yelled, 'Be quiet, Tiffany! We're all rooting for you.' It's TANTRUM!",
"Two cute cartoon eyes staring at you can feel out of place when a spinning punch comes down from the middle of its face. If you want a nose job, it'll rearrange yours for free. Don't worry about the cost. It doesn't bill the dead for rhinoplasty. It's TANTRUM!",
"From San Diego, California, prepare to throw hands with TANTRUM!",

# END GAME
"This bot's builder is one of the youngest in the bunch. He's so young he packs a brown bag lunch. He's new school, that is true, but he knows his bot will kill you... END GAME!",
"His bot is... my precious. You. Shall. Not. LAST! It's END GAME!",
"This young bot's matured so much it's time for its bot-mitsfa. Hava notkillyou, hava notkillyou, it's END GAME!",
"This Jack is here to slay some giants and he's ready to stalk you down. He's not looking for fame, but you'll remember his name. It's END GAME!",
"You've made it through all the levels and collected all the treasure. Now it's time to face the final boss. You're at the END GAME!",
"Straight from down under, his vertical spinner brings the thunder. You wouldn't want to get in a scrum with this young chum. It's END GAME!",
"These young guns from New Zealand will leave you squealing. Big time pain is what you'll be feeling. Hope you've brought your extra lives, because you're about to meet END GAME!",
"This bot is driven by cool guy who have it made in the shades. Wheeling and dealing, all the way from New Zealand. Now you kiwi, now you don't. It's END GAME!",
"This bot has more hits than Bon Jovi and you're going out in a blaze of gore-y. Shot through your parts 'cause you'll get maimed. You're getting played by END GAME!",
"It may be a kiwi, but it's about to go bananas. It swipes you on the left, it swipes you on the right, it peels you down the middle and.. ugh, it really bites. He roughed up Gruff, now you're going to get the same. It's END GAME!",
"Goonies, you're in for a rocky road. It'll cut you in Chunks, it'll beat you silly, then rock your world like One-Eyed Willy. It's victory dance is called the Truffle Scuffle. Heeeeey yoooou guuuuuys! It's END GAME!",
"Dang, these builders look fresh. These young hot-shots must get their sunglasses from Slay-Ban because their bot throws blows as hard as it throws shade. It's END GAME!",
"This match is over before it begins. R.I.P. you apart with its lethal spins. When it's all done, you'll take the walk of shame. Ladies and gentlemen, welcome to END GAME!",
"This next bot was born in New Zealand like the great Russell Crowe, but tonight, he's an American gangster here to crush his foes. His engineers have a beautiful mind, they dream of torture and pain. Give the thumbs down and he'll kill the opponent. ARE YOU NOT ENTERTAINED!? It's END GAME!",
"From Auckland, New Zealand, tick tock... tick tock... this battle's about to start. Time's up, it's END GAME!",
"From Auckland, New Zealand, the destructive spinner in its prime, about to commit a robot crime. It's safe to say you're out of time. It's END GAME!",
"He comes from the land that kept Peter Jackson inspired. New Zealand's still there but this bot burned down The Shire. There's no fellowship, no towers, no Frodo, no ring. We're fighting for a Nut and it's the return of the king... it's END GAME!",
"He comes from the land where the Zealand is New. He's traveled across ocean and he's coming for you. It's not the maid or Colonel Mustard, it doesn't matter what room. The only clue that you need is that his name spells your doom. It's END GAME!",
"You can't kill a bot who comes from New Zealand. You may eat a kiwi but you can never beat him. It's not Australian, it's Australian adjacent and if you face him, just forfeit. Let him kill your replacement. It's END GAME!",
"I was thinking, this team name has end at the beginning. Seems backwards but it kind of explains how they're winning. They're endearing but their opponents are endangered, that's for sure. Face them and there's an endless amount of pain to endure. if you endeavor to fight them, I can't endorse that thought 'cause END GAME has ended every enemy they fought. Give it up for END GAME!",
"This thing is a slasher just like Halloween. This isn't a kid's game. This isn't Red Rover, it's the end of the line. Lights out! Game over. It's END GAME!",
"From Auckland, New Zealand, these Kiwis are ready to bring you the Fight of the Concords. It's END GAME!",
"Once upon a time in Hollywood, this team won the Giant Nut. Now, these natural born killers are in Sin City and they're kicking butt. They were death proof before winning battles from dusk till dawn, now it's the same story except they're dressed like the reservoir dogs. By the way, did you know that in New Zealand, they call Golden Bolt a royale with cheese? Pretty crazy, huh? Give it up for END GAME!",
"This team of dreamers made a serious off-season glow-up. Started dressing extra spiffy, while they made robots blow up. They're gonna hoist the Golden Bolt and watch it sparkle. Going from Suits to royalty, like Meghan Markle. It's END GAME!",
"They have a Monopoly on winning. Setting all kinds of records. If facing them's a Risk, this is chess, it ain't checkers. Sorry. You tried to climb the ladder, but now you're headed down the chute because being this game is a Trivial Pursuit. Give it up for END GAME",
"A kiwi is a fruit that is green, you see. It's healthy and sweet. It tastes great on acai. But this kiwi robot sees only blood red and sprinkles you with chia as it takes off your head. Give it up for END GAME!",
"Hailing from New Zealand, where the Hobbits call home. It's the mechanical magician, call him Gandalf the Crow, the reigning world champion, the head of the class. And if he's your matchup, YOU! SHALL NOT! PASS! The bot who calls the Giant Nut his precious. It's END GAME!",
"Put the controller down, son. This game's too violent for beginners, it's rated M for murderous. These winners eat Noobs for dinner. A perfect tool of Modern Warfare with Sonic speed, that's the scenario. It's game over when he pops you like, 'It's-a me, Mario.' Here to put you in a pine Xbox, it's END GAME!",
"This bot shares its name with a song by Taylor Swift, 'cause he'll publicly humiliate you if he gets miffed. He's got a long list of robots that he's beat and maimed. He's got a Blank Space, baby, and he'll write your name. Look what you made him do. It's END GAME!",
"They could fight for days on end, until you're at the end of your rope. Facing them is a dead-end, it won't end on a positive note. They've gone off the deep end, it's your end of days. So, please be guarded, 'cause you won't end their reign. It's endless, and it's just getting started. Give it up for END GAME!",
"From Auckland, New Zealand, former winners of the Giant Nut, Golden Bolt, and Best-Dressed Team Award, give it up for END GAME!",
"These vets are highly decorated. They've won all the accolades Their trophy case is so bright they gotta wear shades. Left Gary Gin and Free Shipping salting margaritas with their tears, Hoover Damned JackPot to hell when they busted its gears. Now they'll smoke SAWBLAZE, turn Jamison Go into Jamison Stop because winning's the name of the game and they'll end up on top. It's END GAME!",

# BITE FORCE
"Here to devour the competition, this is BITE FORCE!",
"This vicious beast doesn't even think it's in a competition! He thinks it's a buffet line. Makes some noise for BITE FORCE!",
"It came for the food, but it stays for the mayhem. Here's BITE FORCE!",
"It's so tough when it goes to the dentist, it drills him. Keeping Novocaine in business, it's BITE FORCE!",
"From Mountain View, California, it's the Minister of Maul, the Prince of Pierce, the Reigning King of Crush. It's BITE FORCE!",
"It was the champ with the clamp. Now it's the star with the bar. Give it up for the undisputed ill-reputed, batteries included, BITE FORCE!",
"Cover your ears. This bot bites harder than Mike Tyson. It's the undisputed heavyweight champion of the Box. It's BITE FORCE!",
"Come on down! You're the next victim on The Bite is Right! The undefeated reigning champion. It's BITE FORCE!",
"Straight from... the dark side, Luke out, Yoda not know who you're messing with. Here to Leia you out, it's BITE FORCE!",
"It's hungry and ready for gore. It'll chew you up and devour you in one gigabyte. It's every dental hygienist's worst nightmare. BITE FORCE!",
"Making your bot look straight-up lousy, ending fights quicker than Rhonda Rousey. You're about to be octa-gone. It's BITE FORCE!",
"Straight from Silicon Valley, here comes another tech boom. Bring on the kill-ionaires and a big crash. It's BITE FORCE!",
"He's a former champ, ready to reclaim his crown. If you get back up, it'll just know you right back down. Make no mistake, he's here to run this town. It's BITE FORCE!",
"A long time ago, in a galaxy far, far away, a bot was designed to stop the dark side. Today the force awakens. It's BITE FORCE!",
"Chewing up bots in murderous routes, it's last two fights have been complete knockouts. It shows no remorse. It's BITE FORCE!",
"It's gone undefeated, not a single mistake. A path of destruction it left in its wake. It already has a Giant Nut, now it's going for two. Just one more bot for it to rip through. Make some noise for BITE FORCE!",
"This bot will chew you up like gum, beat you like a drum, then leave you looking dumb. If it's a shark, you're the chum. BITE FORCE!",
"4 out of 5 dentists recommend you stay as far away from this bite as you can. The fifth one's dead. Here to slay, with more pain than tooth decay, it's BITE FORCE!",
"So deadly, it's from Kill-icon Valley. Hurts worse than Uber during surge pricing. Ding! Your driver Paul is just three minutes away... from totally destroying you! It's BITE FORCE!",
"All hail the reigning king. Let's hear it for the undeniable, undefeated, twice-repeated BattleBots champion of the world, you know of course the one, the only BITE FORCE!",
"It's the reigning champ. I said it's the reigning champ. No, you're not having déjà vu. The Giant Nut, this bot's won two. It's hungry for more and you're the next course. Bon appetit. It's BITE FORCE!",

# Tombstone
"Here to read your last rites, the one, the only, TOMBSTONE!",
"It doesn't enter the arena. Oh, no. It leads a funeral procession! Prepare to meet the Grim Reaper. It's TOMBSTONE!",
"Its spinning arm can liquidate your assets faster than the IRS. Make some noise, it's TOMBSTONE!",
"If it was a Christmas carol, it would be called 'Violent Night'. Here to put you to sleep, it's TOMBSTONE!",
"It spins faster than a Cat-5 hurricane. The undisputed master of disaster, TOMBSTONE!",
"This driver should change his name to Ray Killings. Here comes the boom! It's TOMBSTONE!",
"Ashes to ashes, dust to dust, you’re about to get crushed. Responsible for more hits than the CIA, it’s TOMBSTONE!",
"Bring the bride and the doom! It's your getting day! It's TOMBSTONE!",
"When you go against this bot, your epitaph will read I tried and I died. Rest in pieces. It's TOMBSTONE!",
"It's a grim reaper with a micro-chip on his shoulder. Back from the dead to take the throne, it's TOMBSTONE!",
"This bot is more deadly than botulism and Mota Controlla Ebola. On a roll and racking up a death toll, it's TOMBSTONE!",
"Please rise for the reigning king, the prince of pain, the duke of death. Hear ye, hear ye, His Royal Die-ness. The one, the only, TOMBSTONE!",
"Call the dog catcher 'cause this hound from hell needs a muzzle. If the devil had a pet, it's what he would cuddle. It's TOMBSTONE!",
"This legendary bot belongs on Mount Crush-more. It's bad enough to make you say Hoover DAYUM! It's a national treasure. It's TOMBSTONE!",
"Fee Fi Fo Fum! Face this bot and you'll be done. Bringing the pain, it's the giant of the game. You know his name. It's TOMBSTONE!",
"It came with one mission: to pillage and maim. The record of blemish, every result the same. No matter the bot, no matter how brave, you're gonna end up in your grave. It's TOMBSTONE!",
"When the reaper comes knocking at your door, it comes with a blade with spins galore. When you ask for whom the death tolls, it's this bot crushing more souls. It's TOMBSTONE!",
"This bot's been here so many times, I'm running out of rhymes. But my beard looks good. It's TOMBSTONE!",
"It's guilty of the seven deadly spins and it's about to unleash bar-mageddon. It's so evil it will never atone. It's TOMBSTONE!",
"This bots violence causes silence. It can't be mistaken, all your tanks and your bombs, and your bombs and your guns can't destroy this bot. Here to chop thee like a zomba-a-a oh-oh-oh. TOMBSTONE!",
"From the book of BattleBots, Chapter 25, Verse 17. And this bot will strike down upon thee with great vengeance and furious anger those who attempt to enter the BattleBox. And you will know its name when it lays down its vengeance upon thee! TOMBSTONE!",
"He's ranked #4 and he'll do a number on you. He's the prince of darkness, the 2016 champ, here to regain the throne. It's TOMBSTONE!",
"Make way for the four seed, the former champ is back. It's just straight up bad to the bone. It's the angel of death, it's TOMBSTONE!",
"Ray Billings scares everyone, even the brave. Then just like Carlton, he'll dance on your grave. It's not unusual, it's TOMBSTONE!",
"As you approach this tombstone, your heart starts to pound. You open your mouth but can't make a sound. Then you get closer, and closer, and get a clear eye view, and read the ""inscription Here lies you"". It's TOMBSTONE!",
"A-tisket a-tasket, he'll put you in a casket. One by one he has broken his foes, one question about that coffin: you want it open, or closed? It's TOMBSTONE!",
"Prepare to Die Hard. And if you're asking who's the illest, know this bot is unbreakable like its name was Bruce Willis. Remember The Sixth Sense? Well that ending applies 'cause after you lose this fight, you'll realize... I was dead... the whole time... Spoiler alert! Give it up for TOMBSTONE!",
"He's the Godfather of bots and he's beaten plenty of Goodfellas. His legend status is untouchable. Other bots should be jealous. Now he's in the land of casino and his run's just getting started. And after he kills you, we'll call you the departed. Give it up for TOMBSTONE!",
"It'll be a beautiful funeral as your life comes to an end. You'll be carried by pallbearers, six of your friends. In this battle, it's time to test my thesis that if you come too close to him. you'll rest in pieces. It's TOMBSTONE!",
"This bot will steal your will and crush your morale. Lights you up like a shootout at the Corral. He'll fill you with holes and then say with a laugh, 'What was it you wanna know was your epitaph? Ha ha ha ha!' It's TOMBSTONE!",
"Dearly beloved, we are gathered here today to celebrate a thing called Tombstone. Like His Purple Majesty, it's a Prince in the BattleBox dome. The bot is delirious to extend its purple reign. It's already going crazy. Now, it's just straight up insane. There's no controversy and almost nothing you can do. One hit from his blade and you're the artist formerly known as you. This is TOMBSTONE!",
"From Placerville, California, he likes his pizza with pepperoni, pineapple and the blood of his victims. I know, gross, right? Pineapple? *groans* It's TOMBSTONE!"
]

# end of code
